---
title: "Flora and Fauna"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

```{r, include=FALSE}
#loading libraries
library(tidyverse)
library(rvest)
library(httr)
library(leaflet)
library(crosstalk)
```

```{r, include = FALSE}
#loading datasets
garden_info = 
  GET("http://data.cityofnewyork.us/resource/p78i-pat6.csv") |> 
  content("parsed") |>
  janitor::clean_names() |>
  drop_na() |>
   mutate(
    borough = 
      recode(
        borough,
        "B" = "Brooklyn",
        "M" = "Manhattan",
        "X" = "Bronx",
        "R" = "Staten Island",
        "Q" = "Queens"
      )
   )

site_visits = 
  GET("http://data.cityofnewyork.us/resource/xqbk-beh5.csv") |>
  content("parsed") |>
  janitor::clean_names()
```

```{r, include = FALSE}
##merging the data sets for flora and fauna analysis
#cleaning site visit data set so it only includes variables involved in flora and fauna 
site_visits_flora_fauna = site_visits |>
  select(parksid, inspectionid, treesingarden, fruittrees, streettrees, chickens, pond, fishinpond, turtles, totalsidewalkarea) |>
 mutate_at(c('treesingarden', 'fruittrees', 'streettrees', 'chickens', 'pond', 'fishinpond', 'turtles'), as.numeric)

flora_fauna_df= 
  inner_join(garden_info, site_visits_flora_fauna, by = "parksid") 
```

```{r, include = FALSE}
flora_fauna_df = flora_fauna_df |>
  group_by(borough) |>
  mutate(
  "Trees in Garden" = sum(treesingarden),
  "Fruit Trees" = sum(fruittrees),
  "Street Trees" = sum(streettrees),
  "Chickens" = sum(chickens),
  "Pond" = sum(pond),
  "Fish in Pond" = sum(fishinpond),
  "Turtles" = sum(turtles)
  )
```

```{r multi-series bar chart reflecting distribution of flora and fauna features by borough}
flora_fauna_tidy = 
   pivot_longer(
    flora_fauna_df, 
    "Trees in Garden":"Turtles",
    names_to = "item", 
    values_to = "total")

ggplot(flora_fauna_tidy, aes(x = borough, y= total, fill=item)) + 
    geom_bar(position="dodge", stat="identity") +
  labs(title = "Distribution of Flaura + Fauna Features in NYC Gardens",
    x = "Borough",
    y = "Number of Gardens with Each Feature by Borough",
    color = "Flora/Fauna Feature",
    caption = "Data from NYC Open Data"
  ) +
    viridis::scale_fill_viridis(
    name = "Flora/Fauna Feature", 
    discrete = TRUE
  )
```

```{r logistic regression for presence of types of trees by borough, controlling for sidewalk area}
fit_logistic_df =
  flora_fauna_df |>
  select('treesingarden', 'fruittrees', 'streettrees', 'borough', 'totalsidewalkarea') |>
  drop_na() |>
  mutate(
    borough = fct_relevel(borough, "Manhattan")
  )

fit_logistic_treesingarden = 
  fit_logistic_df |>
  glm(treesingarden~ borough + totalsidewalkarea, data = _, family = binomial()) 

fit_logistic_fruittrees = 
  fit_logistic_df |>
  glm(fruittrees ~ borough + totalsidewalkarea, data = _, family = binomial())

fit_logistic_streettrees = 
  fit_logistic_df |>
  glm(streettrees ~ borough + totalsidewalkarea, data = _, family = binomial())

fit_logistic_treesingarden |> 
  broom::tidy() |> 
  mutate(OR = exp(estimate)) |>
  select(term, log_OR = estimate, OR, p.value) |> 
  knitr::kable(digits = 3)

fit_logistic_fruittrees |> 
  broom::tidy() |> 
  mutate(OR = exp(estimate)) |>
  select(term, log_OR = estimate, OR, p.value) |> 
  knitr::kable(digits = 3)

fit_logistic_streettrees |> 
  broom::tidy() |> 
  mutate(OR = exp(estimate)) |>
  select(term, log_OR = estimate, OR, p.value) |> 
  knitr::kable(digits = 3)
```

```{r}
#Interactive Map: Flora and Fauna in Gardens of NYC 
map_data <- flora_fauna_df |>
  select(
    garden_name = gardenname, 
    latitude = lat, 
    longitude = lon, 
    Location = address,
    borough, chickens, fruittrees, streettrees, treesingarden, pond, fishinpond, turtles
  ) |>
  mutate(
    floraandfauna = paste0(
      ifelse(chickens > 0, "Chickens, ", ""),
      ifelse(fruittrees > 0, "Fruit Trees, ", ""),
      ifelse(streettrees > 0, "Street Trees, ", ""),
      ifelse(treesingarden > 0, "Trees in Garden, ", ""),
      ifelse(pond > 0, "Pond, ", ""),
      ifelse(fishinpond > 0, "Fish in Pond, ", ""),
       ifelse(turtles > 0, "Turtles, ", "")
    )
  )

leaflet(map_data) |>
  addTiles() |>
  setView(
    lng = -74.006,  # Longitude of NYC center
    lat = 40.7128,  # Latitude of NYC center
    zoom = 11      # Adjust zoom level (10–13 works well for NYC
  ) |>
  addCircleMarkers(
    ~longitude, ~latitude,
    label = ~paste(garden_name, Location, floraandfauna),
    popup = ~paste0("<b>", garden_name, "</b><br>Borough: ", borough, "<br>FloraandFauna: ", floraandfauna),
    color = "green",
    radius = 6,
    fillOpacity = 0.8
  )
```

